### ISSUE TITLE
怎么关闭easyFloat？

### ISSUE THREAD

**Issue by JiajunLi666** [jingliancui/XamarinFormsEasyFloatSample#1]
请问怎么关闭打开的easyFloat啊？ 权限和打开的按钮实现没有问题，在添加关闭按钮的时候，好像没有找到easyFloat的相关关闭方法，只有打开的show()方法。
新手求解~谢谢

**Comment by jingliancui** [comment]
https://github.com/princekin-f/EasyFloat#%E5%AE%8C%E6%95%B4%E4%BD%BF%E7%94%A8%E7%A4%BA%E4%BE%8B

参考原生的文档即可。

**Comment by JiajunLi666** [comment]
原文档的EasyFloat类中有hide和dismiss的方法，你写的这个包中好像没有，确实不知道该怎么合理调用。求指导应该怎么调用销毁或者隐藏的方法？

**Comment by jingliancui** [comment]
感谢反馈，我这边查一下

**Comment by jingliancui** [comment]
@JiajunLi666 升级到新的nuget包即可，具体编译及运行这个更新了的Sample。
